# Generated by Django 4.1.7 on 2024-11-05 12:08

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0002_alter_userprofile_country_alter_userprofile_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="content",
            field=djrichtextfield.models.RichTextField(blank=True, max_length=3000),
        ),
    ]
